- hosts: bsd
  tasks:
  - name: "reboot host"
    shell: "sleep 5 && shutdown -r now"
    async: 1
    poll: 0
  - name: "wait for host"
    wait_for_connection:
      connect_timeout: 20
      sleep: 5
      delay: 5
      timeout: 300
  - name: "reconfigure networking: freebsd bridge"
    shell: |
        sleep 5
        ifconfig {{ if_east }} promisc up
        ifconfig {{ if_west }} promisc up
        sysctl dev.{{ dev_east }}.fc=0
        sysctl dev.{{ dev_west }}.fc=0
        ifconfig bridge create
        ifconfig bridge0 addm {{ if_east }} addm {{ if_west }} up
